### ISSUE TITLE
Background goes black for less than a second when HQ image is loaded

### ISSUE THREAD

**Issue by demostanis** [manilarome/the-glorious-startpage#24]
Awesome project! It looks better than any other startpage I've seen.
However, after that the HQ background is loaded, the blur filter is removed and before that the HQ background gets loaded, a black background appears for less than a second. It's a little bit annoying.
I'm currently trying to find a workaround.
Any idea why it is doing this?

**Comment by manilarome** [comment]
That's the `body`'s background color. Instead of white(which is more annoying) I set it to `#1a1a1aff`. Setting the background image to the `body` will also create a white "flicker". You can change/fix its behaviour on `js/set-body-background.js` if you want to.

**Comment by demostanis** [comment]
But isn't there a way so it does a smooth transition? Without showing `body`'s color?

**Comment by manilarome** [comment]
Maybe. In google google chrome, it only shows the dark background once on startup then the transition from blur to hq is smooth. While the firefox is flickering on transition.

**Comment by demostanis** [comment]
Removing the `setTimeout` at line 35 in `js/set-body-background.js` fixes it.

**Comment by demostanis** [comment]
Or not... It seems like there's no more blur

**Comment by demostanis** [comment]
I think a fix would be to use an animation to change blur, as it's done [here](https://codepen.io/thatemil/pen/yYmaqG/)

**Comment by manilarome** [comment]
I see. Thanks. Will look into it

**Comment by manilarome** [comment]
It seems that there's a bug in firefox yet to be resolved. Explanation [here](https://stackoverflow.com/questions/57169904/changing-background-image-property-causes-a-flicker-in-firefox).

**Comment by manilarome** [comment]
Fixes: https://github.com/manilarome/the-glorious-startpage/commit/4db08d7b517140c8f00f7340ccaf4892883cee49 https://github.com/manilarome/the-glorious-startpage/commit/f0e192f14d36a9c3eed26409863a68d4d9dd2711
