### ISSUE TITLE
How to I change or add background images?

### ISSUE THREAD

**Issue by snakedye** [manilarome/the-glorious-startpage#30]
I tried putting a webd file in the background folder but nothing appears.

**Comment by danimateo** [comment]
This is the part that handles the background:
```
	_startLazyLoad = () => {
		const date = new Date();
		const hour = date.getHours();

		if (hour >= 6 && hour < 12) {
			this._lazyLoadBackground('morning');

		} else if (hour >= 12 && hour < 18 ) {
			this._lazyLoadBackground('noon');

		} else {
			this._lazyLoadBackground('evening');
		}
	}

```

It searches for .webp pictures with these names in the `assets/backgrounds` folder. Either add new names here or replace the pictures and keep the name.

**Comment by manilarome** [comment]
Just follow @danimateo 's answer.
